# Generated by Django 5.1.6 on 2025-06-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ott', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='watch_later',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
